from typing import Protocol
from decimal import Decimal
from uuid import UUID
from ..dtos import LNMarketsDTO, DeflowExchangeDTO
from ..errors import Error


class PaymentProtocol(Protocol):
    async def validate_coupon(self, coupon_code: str) -> bool: ...
    def get_payment_status(self, user_id: UUID) -> bool: ...
    async def get_total_active_users_with_coupon(self, coupon_code: str) -> int: ...
    async def save_invoice(self, user_id: UUID, invoice): ...
    def publish_event(self) -> None: ...



class DeflowExchangeProtocol(Protocol):
    def create_deposit_pix(self, user_id: UUID, amount: Decimal, payment) -> DeflowExchangeDTO | Error: ...
    def check_payment_status(self, payment_id: str) -> str | Error: ...


class ProviderProtocol(Protocol):
    def create_deposit_in_sats(self, user_id: UUID, final_automation_price: Decimal) -> LNMarketsDTO: ...
    def create_deposit_in_pix(self, user_id: UUID): ...
