# Generated by Django 6.1 on 2026-08-31 18:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid7, editable=False)),
                ('deposit_id', models.UUIDField(db_index=True, unique=True)),
                ('payment_request', models.TextField()),
                ('payment_status', models.CharField(db_index=True, default='PENDING', max_length=20)),
                ('coupon_code', models.CharField(max_length=15, null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
    ]
