# Generated by Django 6.1.1 on 2026-09-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_affiliates_invoice_affiliate_commission_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Affiliates',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='amount_sats',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_brl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
