# Generated by Django 6.1.1 on 2026-09-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_delete_affiliates_remove_invoice_amount_sats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='deposit_id',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
