# Generated by Django 6.1.1 on 2026-10-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_invoice_deposit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='affiliate_commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
