# Generated by Django 6.1.1 on 2026-10-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_invoice_affiliate_commission_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='deposit_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
