from typing import Protocol
from ..dtos import Overview, OverviewPeriod, SidebarStatus


class DashboardProtocol(Protocol):
    def get_overview(self, exchange: str, user_id: str) -> Overview: ...
    def get_overview_period(self, exchange: str, user_id: str, period: str) -> OverviewPeriod: ...
    def get_sidebar_data(self, exchange: str, user_id: str) -> SidebarStatus: ...
    def update_goal_target(self, exchange: str, user_id: str, goal_target: int) -> None: ...
