from typing import Protocol
from ..dtos import Overview, OverviewPeriod


class DashboardProtocol(Protocol):
    def get_overview(self, exchange: str, user_id: str) -> Overview: ...
    def get_overview_period(self, exchange: str, user_id: str, period: str) -> OverviewPeriod: ...
    def update_goal_target(self, exchange: str, user_id: str, goal_target: int) -> None: ...
