# Generated by Django 6.1 on 2026-08-19 16:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
