# Generated by Django 6.0.4 on 2026-10-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hashed_password',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
