from typing import Protocol
from ..dtos import ConfigurationDTO, ApiDTO


class AutomationProtocol(Protocol):

    def add_activated_automation(self, exchange: str, user_id: str): ...
    def get_configuration(self, exchange: str, user_id: str) -> ConfigurationDTO: ...
    def get_status_automation(self, exchange: str, user_id: str) -> bool: ...
    def get_api(self, exchange, user_id) -> ApiDTO: ...
    def save_api(self, exchange, user_id, api_data: ApiDTO): ...
    def save_configuration(self, exchange, user_id: str, configuration: ConfigurationDTO) -> None: ...
    def remove_activated_automation(self, exchange: str, user_id: str): ...
    def publish_event(self, channel, payload): ...
