from collections.abc import AsyncIterator
from typing import Protocol
from decimal import Decimal
from ..dtos import CredentialsDTO, ConfigurationDTO, AllOpenOrders, BuyOrderDTO, SellOrderDTO


class AutomationExecutorProtocol(Protocol):

    def add_buy_order(self, email: str, new_order: BuyOrderDTO): ...
    async def get_credentials(self, email) -> CredentialsDTO: ...
    async def get_configuration(self, email: str, credentials: CredentialsDTO) -> ConfigurationDTO: ...
    async def get_all_open_orders(self, email: str, credentials: CredentialsDTO) -> list[AllOpenOrders | BuyOrderDTO]: ...
    async def save_closed_order(self, order_id: str, profit: Decimal) -> None: ...
    def update_last_buy_up(self, email: str, entry_price: Decimal): ...
    def update_last_buy_down(self, email: str, entry_price: Decimal): ...
    def update_wallet_balance_buy(self, email: str, margin_used: Decimal): ...
    def update_wallet_balance_sale(self, email: str, margin_used: Decimal, net_profit: Decimal): ...
    def remove_sold_order(self, email: str, order_id: str): ...
    def clear_user_memory_state(self, email: str): ...


class WSLNMarketsProtocol(Protocol):

    def add_activated_automation(self, email: str) -> None: ...
    def get_all_activated_automations(self) -> list[str]: ...
    async def synchronize_websocket(self,) -> None: ...
    async def subscribe_channel(self, channel: str) -> AsyncIterator[dict]: ...
    def remove_activated_automation(self, email: str): ...

































class CacheProtocol(Protocol):
    async def add_activated_automation(self, email: str): ...

    async def get_all_activated_automations(self) -> list[str]: ...

    def subscribe_channel(self, channel: str) -> AsyncIterator[dict]: ...


class MemoryProtocol(Protocol):
    def add_activated_automation(self, email: str) -> None: ...

    def get_synchronized_websocket(self,) -> bool: ...
    def get_synchronized_references(self, email: str) -> bool: ...
    def get_credentials(self, email: str) -> CredentialsDTO | None: ...
    def get_configuration(self, email: str) -> ConfigurationDTO | None: ...
    def get_all_activated_automations(self) -> list[str]: ...

    def set_synchoronized_websocket(self,) -> None: ...
    def set_credentials(self, email: str, credentials: CredentialsDTO): ...
    def set_configuration(self, email: str, configuration: ConfigurationDTO): ...
    def set_all_open_orders(self, email: str, all_open_orders: list[AllOpenOrders | BuyOrderDTO]): ...
    def set_all_activated_automations(self, all_activated_automations: list[str]) -> None: ...

    def update_references(self, email: str, all_open_orders: list[AllOpenOrders | BuyOrderDTO]): ...

    def remove_and_clear_user_memory_state(self, email: str): ...


class ExchangeProtocol(Protocol):
    async def open_purchase_order(self, credentials:CredentialsDTO, configuration:ConfigurationDTO) -> BuyOrderDTO: ...
    async def close_profitable_orders(self, credentials:CredentialsDTO, order_id: str) -> SellOrderDTO: ...
    async def get_current_wallet_balance(self, credentials:CredentialsDTO) -> Decimal: ...
    async def get_all_open_orders(self, credentials:CredentialsDTO) -> list[AllOpenOrders | BuyOrderDTO]: ...


class NotifierProtocol(Protocol):
    async def send_buy_message(self, entry_price: Decimal): ...
    async def send_sell_message(self, profit: Decimal): ...
