from collections.abc import AsyncIterator
from typing import Protocol
from decimal import Decimal
from ..dtos import CredentialsDTO, ConfigurationDTO, AllOpenOrdersDTO, BuyOrderDTO, SellOrderDTO
from uuid import UUID


class AutomationExecutorProtocol(Protocol):
    def add_buy_order(self, user_id: UUID, new_order: BuyOrderDTO): ...
    async def get_requirements(self, user_id: UUID, exchange: str) -> tuple[CredentialsDTO, ConfigurationDTO]: ...
    async def get_all_open_orders(self, user_id: UUID, credentials: CredentialsDTO) -> tuple[list[AllOpenOrdersDTO | BuyOrderDTO], float]: ...
    async def save_closed_order(self, user_id: str, sold_order: SellOrderDTO) -> None: ...
    def update_last_buy(self, user_id: UUID, entry_price: Decimal, BUY_UP: bool): ...
    def update_wallet_balance(self, user_id: UUID, margin_used: Decimal, net_profit: Decimal = Decimal("0"), BUY: bool = False): ...
    async def update_dashboard_overview(self, user_id: UUID, margin_used: Decimal, BUY: bool): ...
    async def update_total_patrimony(self, user_id: UUID, total_patrimony: Decimal) -> None: ...
    def remove_sold_order(self, user_id: UUID, order_id: str): ...
    def clear_user_memory_state(self, user_id: UUID): ...
    async def closed_orders_today(self, user_id: str) -> int: ...



class WSExchangeProtocol(Protocol):
    def add_activated_automation(self, user_id: UUID, exchange: str) -> None: ...
    def get_all_activated_automations(self) -> list[tuple[UUID, str]]: ...
    async def synchronize_websocket(self, exchange: str) -> None: ...
    async def subscribe_channel(self, channel: str) -> AsyncIterator[dict]: ...
    def remove_activated_automation(self, user_id: UUID): ...
    async def save_btc_price(self, btc_usd_price): ...


class ExchangeProtocol(Protocol):
    async def open_purchase_order(self, user_id: UUID, credentials: CredentialsDTO, configuration: ConfigurationDTO) -> BuyOrderDTO: ...
    async def close_profitable_orders(self, user_id: UUID, credentials: CredentialsDTO, order_id: str) -> SellOrderDTO: ...
    async def get_current_wallet_balance(self, credentials: CredentialsDTO) -> Decimal: ...
    async def get_all_open_orders(self, credentials: CredentialsDTO) -> tuple[list[AllOpenOrdersDTO | BuyOrderDTO], float]: ...


class NotifierProtocol(Protocol):
    async def send_buy_message(self, entry_price: Decimal, all_open_orders: int): ...
    async def send_sell_message(self, profit: Decimal, all_open_orders: int, user_id: str): ...
