# Generated by Django 6.0.7 on 2026-07-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedOrder',
            fields=[
                ('order_id', models.CharField(primary_key=True, serialize=False)),
                ('profit', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'closed_orders',
            },
        ),
    ]
