# Generated by Django 6.0.8 on 2026-08-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
