# Generated by Django 6.0.8 on 2026-08-06 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_closedorder_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closedorder',
            old_name='created_at',
            new_name='closed_at',
        ),
    ]
