# Generated by Django 6.1.1 on 2026-09-23 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
        ('authentication', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('liquid_address', models.CharField(max_length=100, unique=True)),
                ('promotion_description', models.TextField(blank=True, null=True)),
                ('terms_accepted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.user', unique=True)),
            ],
            options={
                'db_table': 'affiliate',
            },
        ),
        migrations.DeleteModel(
            name='Affiliates',
        ),
    ]
