# Generated by Django 6.1.1 on 2026-09-23 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_affiliate_delete_affiliates'),
        ('authentication', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
    ]
