# Generated by Django 6.1.1 on 2026-09-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_alter_affiliate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='promotion_description',
            field=models.TextField(default=''),
        ),
    ]
