# Generated by Django 5.2.7 on 2025-10-26 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('preco_referencia', models.IntegerField(default=0)),
                ('limite_margem', models.IntegerField(default=0)),
                ('percentual_lucro', models.DecimalField(decimal_places=6, default=0, max_digits=6)),
                ('percentual_variacao_compra', models.DecimalField(decimal_places=6, default=0, max_digits=6)),
                ('percentual_seguranca_liquidacao', models.DecimalField(decimal_places=6, default=0, max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
