# Generated by Django 5.2.7 on 2025-10-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configautomacao',
            name='id_task',
            field=models.BooleanField(default=False),
        ),
    ]
