# Generated by Django 5.2.7 on 2025-10-29 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_invoicespagos_delete_configautomacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicespagos',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoicespagos',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_pagos', to=settings.AUTH_USER_MODEL),
        ),
    ]
