# Generated by Django 5.2.8 on 2025-12-03 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_alter_invoicespagos_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoicesPagos',
        ),
    ]
